version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: leadmanagement-frontend
    environment:
      - NODE_ENV=production
      - API_URL=${API_URL:-http://localhost:5000}
    ports:
      - "4200:80"
    networks:
      - leadmanagement-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  leadmanagement-network:
    driver: bridge 